### ISSUE TITLE
couldn't run proton.py

### ISSUE THREAD

**Issue by KeshavaMaringanti** [xenon-19/Gesture-Controlled-Virtual-Mouse#11]
![2022-04-05](https://user-images.githubusercontent.com/92877573/161687969-f4d80076-9a40-4606-b9a6-b1f1aee1311a.png)

I'm getting the following error when I'm trying to run this code
Could you plz help me

**Comment by ankit-4129** [comment]
1. what python version are you using ? as mentioned in readme use python 3.8.5

2. try to execute below code and share your result.
```
from threading import Thread
from time import sleep

class Obj:

    def __init__(self):
        pass

    def start(self):
        for _ in range(3):
            print('in start')
            sleep(1)

obj = Obj()

t = Thread(target = obj.start)
t.start()

for _ in range(3):
    print('in main')
    sleep(0.3)

t.join()
```

**Comment by KeshavaMaringanti** [comment]
![2022-06-10](https://user-images.githubusercontent.com/92877573/173019671-9be3aea0-7a50-48ca-aaec-421d28edc2fc.png)
