### ISSUE TITLE
This is the error i got

### ISSUE THREAD

**Issue by nikhilmathewfrancis98** [xenon-19/Gesture-Controlled-Virtual-Mouse#13]
![error1](https://user-images.githubusercontent.com/62801039/165141270-97a507ad-a7d1-4b7b-88ea-9d5312bc6c0e.png)
![error2](https://user-images.githubusercontent.com/62801039/165141276-2afb0f1f-5ee3-4103-bb62-eaa0bf69a545.png)

**Comment by Viral-Doshi** [comment]
Try uninstalling opencv-python and installing it again with pip. Let us know the updates.

**Comment by ankit-4129** [comment]
requirments.txt has been updated.
to resolve the issue please run

`pip uninstall comtypes`
`pip install comtypes==1.1.11`
