### ISSUE TITLE
Now output showm

### ISSUE THREAD

**Issue by IVANKOSTARK** [xenon-19/Gesture-Controlled-Virtual-Mouse#27]
Out put not shown
![error](https://user-images.githubusercontent.com/95754702/212875121-f97f39d1-c651-4885-854f-59d1b534b74e.JPG)

**Comment by Shailagni07** [comment]
Successfully run but output isn’t shown plz help me out of this🙏🏻
![image](https://user-images.githubusercontent.com/99985010/233895580-1d3c041e-3597-4e0b-bd14-bf936dc75cd6.jpeg)

**Comment by Shailagni07** [comment]
![Uploading 5084d28c-ae28-476f-8a8d-ed992c7a0dd2.jpeg…]()
