### ISSUE TITLE
Windows Interface "Gui"

### ISSUE THREAD

**Issue by AndrioJonatas** [xenon-19/Gesture-Controlled-Virtual-Mouse#4]
Hi, I don't understand programming could you make a basic executable Windows Interface "Gui" version of this for me?

**Comment by Viral-Doshi** [comment]
We understand your concern, We will soon upload a .exe. file which will help you run Virtual Mouse and Voice Assistant  it in your local machine just by double clicking it ! Stay tuned till then.

**Comment by AndrioJonatas** [comment]
> Compreendemos sua preocupação. Em breve enviaremos um .exe. que irá ajudá-lo a executar o Virtual Mouse e o Voice Assistant em sua máquina local com um clique duplo! Fique ligado até então.

**Comment by AndrioJonatas** [comment]
> Compreendemos sua preocupação. Em breve enviaremos um .exe. que irá ajudá-lo a executar o Virtual Mouse e o Voice Assistant em sua máquina local com um clique duplo! Fique ligado até então.

Can you send me I can send you a donation ...

**Comment by AndrioJonatas** [comment]
> Compreendemos sua preocupação. Em breve enviaremos um .exe. que irá ajudá-lo a executar o Virtual Mouse e o Voice Assistant em sua máquina local com um clique duplo! Fique ligado até então.
