### ISSUE TITLE
process finished with exit code 0 but I haven't seen any interface

### ISSUE THREAD

**Issue by KeshavaMaringanti** [xenon-19/Gesture-Controlled-Virtual-Mouse#5]
![2021-11-09](https://user-images.githubusercontent.com/92877573/140946393-c83eb2fb-8c86-4852-aa8e-5ebb6df056dd.png)

I have installed all the modules. But getting 5 errors
I have run the code successfully
I got 'Process finished with exit code 0'
But cant see the result

**Comment by xenon-19** [comment]
Do provide more details.
Have you made any changes to code?
Which file are you running ?

**Comment by KeshavaMaringanti** [comment]
File name : Gesture_Controller.py
Run using Pycharm
I haven't made any changes in the code.
All the modules from given instructions are installed.
configuration is also set on the script path.
After running the program I can't see any interface or webcam.

**Comment by xenon-19** [comment]
The file Gesture_Controller.py has no driver code.
You are supposed to run Proton.py (mentioned in readme, step 6).
If you want to run Gesture_Controller.py directly, you will have to uncomment the driver code (last 2 lines of the file).

**Comment by KeshavaMaringanti** [comment]
Ok thanks. I will try now

**Comment by KeshavaMaringanti** [comment]
Thanks alot now the code running successfully
