### ISSUE TITLE
Proton isn't working

### ISSUE THREAD

**Issue by chiragnahata** [xenon-19/Gesture-Controlled-Virtual-Mouse#6]
Hi, 
I tried executing https://github.com/xenon-19/Gesture-Controlled-Virtual-Mouse but proton isn’t working. It is not recognising my commands. Please help as soon as possible. It is also not launching the Gesture Controller.

Chirag Nahata
+917439611385

**Comment by xenon-19** [comment]
Do provide with more details.
Which file did you execute, attach images as well.

**Comment by chiragnahata** [comment]
I executed the command python Proton.py. Actually the interface came up but
it doesn't recognise anything

Chirag Nahata

**Comment by Viral-Doshi** [comment]
Please ensure you are using the word Proton before giving it the command. Eg. Proton what is today's date ?
Any command which doesn't begin with the word Proton is treated as Noise by the Voice Assistant. If you are giving it the right command and no output is still showing up, try to use a microphone.

**Comment by chiragnahata** [comment]
Yes i am giving the command proton only using a microphone but still
nothing happens

Chirag Nahata

**Comment by Viral-Doshi** [comment]
Please mail me with the video / screen recording of the command you are providing and the output which pops up. In case of errors please provide the error description. We will try our best to help.
Regards.

**Comment by chiragnahata** [comment]
Sure, will do that.

Chirag Nahata

**Comment by chiragnahata** [comment]
Here is the video of the issue - https://drive.google.com/file/d/1rD5I9PCz00-aPY7RoQZWF9_WNhCZ_V-Q/view?usp=sharing

**Comment by Viral-Doshi** [comment]
Ok so as mentioned in the error log in your command prompt, PyAudio works with only specific versions of Python. Please use the Python version mentioned in ReadME (3.8.5). PyAudio doesn't support Python 3.10. If it still doesnt work uninstall the latest version of python and download version 3.8.5 and then install the library dependancies.
