### ISSUE TITLE
error in pip install -r requirements.txt

### ISSUE THREAD

**Issue by aniketsethiya** [xenon-19/Gesture-Controlled-Virtual-Mouse#8]
![Screenshot (175)](https://user-images.githubusercontent.com/79057285/157275049-e2d67eab-eed0-4e2b-a164-c336f2a4b783.png)

**Comment by Viral-Doshi** [comment]
The error states C++ 14.0 is required. Try downloading it from Build tools and give it a try. I have never come across such an error.
