### ISSUE TITLE
Error while running proton.py

### ISSUE THREAD

**Issue by awanishtiwari97** [xenon-19/Gesture-Controlled-Virtual-Mouse#9]
After configuring all the files and requirements.txt when i go to run the file named proton.py it is showing error that the libraries which are written for import is saying that it is not found.
I have attached the screenshot for the reference.
![WhatsApp Image 2022-03-26 at 11 31 27 AM](https://user-images.githubusercontent.com/63773588/160246524-32f9d180-7e55-4a7c-9855-b418f10a5332.jpeg)

**Comment by Viral-Doshi** [comment]
Try downloading pywin32 library independently.  You will get many alternatives from the net.
Try: pip install pywin32
